spring.application.name=TicketingSystem
spring.datasource.url = jdbc:postgresql://localhost:5432/project
spring.datasource.username = postgres
spring.datasource.password = 3699
spring.datasource.driver-class-name = org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto = update
